import React from 'react';
import { Shield, Award, Users, TrendingUp } from 'lucide-react';

const AboutSection = () => {
  const achievements = [
    {
      icon: Users,
      number: "50,000+",
      label: "Trusted Users",
      description: "Professionals worldwide rely on our recommendations"
    },
    {
      icon: TrendingUp,
      number: "$2M+",
      label: "Commissions Earned",
      description: "Total earnings generated by our community"
    },
    {
      icon: Award,
      number: "4.9/5",
      label: "Trust Rating",
      description: "Average rating from verified users"
    },
    {
      icon: Shield,
      number: "100%",
      label: "Transparency",
      description: "Full disclosure on all affiliate relationships"
    }
  ];

  return (
    <section className="py-20 bg-gradient-to-br from-gray-50 to-blue-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          {/* Content */}
          <div>
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Your Trusted Partner in 
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
                {' '}Premium Opportunities
              </span>
            </h2>
            
            <div className="space-y-6 text-lg text-gray-600 leading-relaxed">
              <p>
                At TechToolsReviews, we specialize in identifying and reviewing the highest-paying 
                affiliate programs across technology, finance, travel, and lifestyle sectors. Our 
                mission is to connect professionals with premium opportunities that generate 
                substantial income.
              </p>
              
              <p>
                Founded by industry experts with over a decade of experience in affiliate marketing, 
                we understand what it takes to build successful partnerships. Every program we 
                recommend has been thoroughly vetted for reliability, conversion rates, and 
                commission potential.
              </p>
              
              <p>
                We believe in complete transparency. All our reviews include honest assessments, 
                clear commission structures, and real-world performance data. When you succeed, 
                we succeed.
              </p>
            </div>

            <div className="mt-8 p-6 bg-white rounded-xl shadow-lg border-l-4 border-blue-600">
              <h3 className="text-xl font-bold text-gray-900 mb-2">Our Commitment</h3>
              <p className="text-gray-600">
                We only recommend programs we would use ourselves. Every affiliate partnership 
                is disclosed, and we prioritize your success over short-term gains.
              </p>
            </div>
          </div>

          {/* Achievements Grid */}
          <div className="grid grid-cols-2 gap-6">
            {achievements.map((achievement, index) => (
              <div key={index} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-shadow duration-300">
                <div className="flex items-center justify-center w-12 h-12 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg mb-4">
                  <achievement.icon className="h-6 w-6 text-white" />
                </div>
                <div className="text-2xl font-bold text-gray-900 mb-1">
                  {achievement.number}
                </div>
                <div className="text-sm font-semibold text-blue-600 mb-2">
                  {achievement.label}
                </div>
                <div className="text-xs text-gray-600 leading-relaxed">
                  {achievement.description}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutSection;